# Generated by Django 4.0 on 2022-08-10 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_services'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название Отделения')),
                ('slug', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Отделение',
                'verbose_name_plural': 'Отделения',
            },
        ),
        migrations.CreateModel(
            name='PersonalPostPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название Вакансии')),
                ('slug', models.CharField(max_length=255)),
                ('department', models.ManyToManyField(related_name='department_for_post', to='main.Department', verbose_name='Отделения')),
            ],
            options={
                'verbose_name': 'Вакансия',
                'verbose_name_plural': 'Вакансии',
            },
        ),
        migrations.CreateModel(
            name='MedicalPersonal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='site_media', verbose_name='Изображение')),
                ('full_name', models.CharField(max_length=100, verbose_name='ФИО')),
                ('experience', models.IntegerField(verbose_name='Стаж работы (лет)')),
                ('category', models.CharField(choices=[('вища_категорія', 'Вища категорія'), ('середня_категорія', 'Середня категорія'), ('intert', 'Интерн')], default='intert', max_length=50)),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('post', models.ManyToManyField(related_name='department_for_personal_post', to='main.PersonalPostPosition', verbose_name='Вакансии')),
            ],
        ),
    ]
