# Generated by Django 4.0 on 2022-08-10 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_department_personalpostposition_medicalpersonal'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicalpersonal',
            options={'verbose_name': 'Персонал', 'verbose_name_plural': 'Персонал'},
        ),
        migrations.RemoveField(
            model_name='medicalpersonal',
            name='category',
        ),
        migrations.AddField(
            model_name='medicalpersonal',
            name='category_steep',
            field=models.CharField(choices=[('vishya_categoriya', 'Вища категорія'), ('serednya_categoriya', 'Середня категорія'), ('intert', 'Интерн'), ('medsestra', 'Медсестра'), ('sanitar', 'Санитар')], default='intert', max_length=50),
        ),
    ]
