# Generated by Django 4.0 on 2022-08-11 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_medicalpersonal_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalpersonal',
            name='phone',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='medicalpersonal',
            name='category_steep',
            field=models.CharField(choices=[('vishya_categoriya', 'Вища категорія'), ('serednya_categoriya', 'Середня категорія'), ('intern', 'Интерн'), ('medsestra', 'Медсестра'), ('sanitar', 'Санитар'), ('no_category', 'Без категоріi')], default='intern', max_length=50),
        ),
    ]
