# Generated by Django 4.0 on 2022-08-11 18:19

from django.db import migrations, models
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_medicalpersonal_phone_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Контент')),
                ('image', models.FileField(upload_to='site_media', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Check-Up Информация',
                'verbose_name_plural': 'Check-Up Информация',
            },
        ),
        migrations.CreateModel(
            name='CheckUpItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название Check-UP')),
                ('image', models.FileField(upload_to='site_media', verbose_name='Картинка Check-UP')),
                ('header_title', models.CharField(max_length=100, verbose_name='Заголовок хедера')),
                ('header_subtitle', models.CharField(max_length=100, verbose_name='Подзаголовок хедера')),
                ('header_image', models.FileField(upload_to='site_media', verbose_name='Картинка хедера')),
                ('description', models.TextField(verbose_name='Описание Check-UP')),
                ('content_title', models.CharField(max_length=100, verbose_name='Заголовок Check-UP')),
                ('content', django_quill.fields.QuillField(verbose_name='Контент')),
                ('slug', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Check-Up',
                'verbose_name_plural': 'Check-Up',
            },
        ),
    ]
