# Generated by Django 4.0 on 2022-08-11 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_checkup_checkupitems'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkupitems',
            name='header_subtitle',
        ),
    ]
