# Generated by Django 4.0 on 2022-08-13 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_checkupitems_header_subtitle'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactsInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=100, verbose_name='Телефон')),
                ('mail', models.CharField(max_length=100, verbose_name='Эл. Почта')),
                ('address', models.CharField(max_length=255, verbose_name='Адресс')),
                ('geolocation', models.TextField(verbose_name='Геолокация (код с гугл карт)')),
                ('viber', models.CharField(max_length=100, verbose_name='VIBER')),
                ('telegram', models.CharField(max_length=100, verbose_name='TELEGRAM')),
                ('instagram', models.CharField(max_length=100, verbose_name='INSTAGRAM')),
                ('facebook', models.CharField(max_length=100, verbose_name='FACEBOOK')),
                ('telegram_notification', models.CharField(max_length=100, verbose_name='Телеграм группа для оповещений')),
            ],
            options={
                'verbose_name': 'Контакты',
                'verbose_name_plural': 'Контакты',
            },
        ),
    ]
