# Generated by Django 4.0 on 2022-08-13 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_contactsinformation'),
    ]

    operations = [
        migrations.AddField(
            model_name='avantagessection',
            name='display_order',
            field=models.IntegerField(default=1, verbose_name='Положение в списке'),
        ),
        migrations.AddField(
            model_name='checkupitems',
            name='display_order',
            field=models.IntegerField(default=1, verbose_name='Положение в списке'),
        ),
        migrations.AddField(
            model_name='services',
            name='display_order',
            field=models.IntegerField(default=1, verbose_name='Положение в списке'),
        ),
    ]
