# Generated by Django 4.0 on 2022-08-14 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_avantagessection_display_order_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=100, verbose_name='Телефон')),
                ('mail', models.CharField(blank=True, max_length=100, null=True, verbose_name='Эл. Почта')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
            ],
            options={
                'verbose_name': 'Заявки (Контакты)',
                'verbose_name_plural': 'Заявки (Контакты)',
            },
        ),
        migrations.AlterField(
            model_name='contactsinformation',
            name='telegram_notification',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Телеграм группа для оповещений'),
        ),
    ]
