# Generated by Django 4.0 on 2022-08-14 08:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_contactform_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactform',
            name='date_created',
            field=models.DateField(default=datetime.date(2022, 8, 14), verbose_name='Дата отправки'),
        ),
    ]
