# Generated by Django 4.0 on 2022-08-14 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_contactform_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactform',
            name='date_created',
            field=models.DateField(blank=True, null=True, verbose_name='Дата отправки'),
        ),
    ]
