# Generated by Django 4.0 on 2022-08-14 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_contactform_date_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=100, verbose_name='Телефон')),
                ('mail', models.CharField(blank=True, max_length=100, null=True, verbose_name='Эл. Почта')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
            ],
        ),
        migrations.RemoveField(
            model_name='contactform',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='contactform',
            name='mail',
        ),
        migrations.RemoveField(
            model_name='contactform',
            name='name',
        ),
        migrations.RemoveField(
            model_name='contactform',
            name='phone',
        ),
        migrations.AddField(
            model_name='contactform',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.clients', verbose_name='Клиент'),
        ),
    ]
