# Generated by Django 4.0 on 2022-08-14 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_clients_options_clients_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactform',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий'),
        ),
    ]
