# Generated by Django 4.0 on 2022-08-14 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_contactform_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactform',
            name='status',
            field=models.CharField(choices=[('new', 'Нова'), ('processing', 'В обробці'), ('complete', 'Завершено')], default='new', max_length=50),
        ),
    ]
