# Generated by Django 4.0 on 2022-08-14 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_contactform_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactform',
            name='status',
            field=models.CharField(choices=[('new', 'Нова'), ('processing', 'В обробці'), ('complete', 'Завершено')], default='new', max_length=50, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='medicalpersonal',
            name='category_steep',
            field=models.CharField(choices=[('vishya_categoriya', 'Вища категорія'), ('serednya_categoriya', 'Середня категорія'), ('intern', 'Интерн'), ('medsestra', 'Медсестра'), ('sanitar', 'Санитар'), ('no_category', 'Без категоріi')], default='intern', max_length=50, verbose_name='Категория'),
        ),
    ]
