# Generated by Django 4.0 on 2022-08-14 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_alter_contactform_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactsinformation',
            name='telegram_notification',
        ),
        migrations.AddField(
            model_name='contactsinformation',
            name='telegram_token',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Телеграм токен для группы оповещений'),
        ),
        migrations.AddField(
            model_name='contactsinformation',
            name='tg_chat_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ИД чата телеграм (для оповещений)'),
        ),
    ]
