# Generated by Django 4.0 on 2022-08-14 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_remove_contactsinformation_telegram_notification_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactsinformation',
            name='telegram_token',
            field=models.TextField(blank=True, null=True, verbose_name='Телеграм токен для группы оповещений'),
        ),
    ]
