# Generated by Django 4.0 on 2022-08-14 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_services_category_services_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='site_media', verbose_name='Изображение (Не обязательно)'),
        ),
        migrations.AlterField(
            model_name='services',
            name='link',
            field=models.CharField(default='#', max_length=100, verbose_name='Ссылка'),
        ),
    ]
