# Generated by Django 4.0 on 2022-08-14 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_alter_services_image_alter_services_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='service_type',
            field=models.CharField(choices=[('consult', 'Консультация'), ('diagnostic', 'Диангостика'), ('service', 'Услуга')], default='consult', max_length=50, verbose_name='Тип Услуги'),
        ),
    ]
