# Generated by Django 4.0 on 2022-08-14 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_services_service_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='display_order',
        ),
    ]
