# Generated by Django 4.0 on 2022-08-14 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_remove_services_display_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='category',
            field=models.ManyToManyField(blank=True, null=True, related_name='department_for_services', to='main.PersonalPostPosition', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='services',
            name='service_type',
            field=models.CharField(choices=[('consult', 'Консультация'), ('diagnostic', 'Диангостика'), ('service', 'Услуга'), ('service_template', 'Макеты')], default='consult', max_length=50, verbose_name='Тип Услуги'),
        ),
    ]
