# Generated by Django 4.0 on 2022-08-14 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_alter_services_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicesInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Контент')),
                ('image', models.FileField(upload_to='site_media', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Услуги Информация',
                'verbose_name_plural': 'Услуги Информация',
            },
        ),
    ]
