# Generated by Django 4.0 on 2022-08-14 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_alter_servicesinfo_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicesinfo',
            old_name='comment',
            new_name='title',
        ),
    ]
