# Generated by Django 4.0 on 2022-08-15 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_rename_comment_servicesinfo_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckUPForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('status', models.CharField(choices=[('new', 'Нова'), ('processing', 'В обробці'), ('complete', 'Завершено')], default='new', max_length=50, verbose_name='Статус')),
                ('date_created', models.DateField(blank=True, null=True, verbose_name='Дата отправки')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.clients', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Заявки (Check-UP)',
                'verbose_name_plural': 'Заявки (Check-UP)',
            },
        ),
    ]
