# Generated by Django 4.0 on 2022-08-20 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_checkupform'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='category',
        ),
    ]
