# Generated by Django 4.0 on 2022-08-20 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_remove_services_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='image',
        ),
        migrations.AddField(
            model_name='department',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='site_media', verbose_name='Изображение (Не обязательно)'),
        ),
    ]
