# Generated by Django 4.0 on 2022-08-20 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_remove_services_link_department_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='link',
        ),
    ]
