# Generated by Django 4.0 on 2022-08-20 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_remove_department_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='service_departament', to='main.department', verbose_name='Выберите отделение'),
        ),
    ]
