# Generated by Django 4.0 on 2022-08-20 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_alter_services_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='slug',
        ),
    ]
