# Generated by Django 4.0 on 2022-08-20 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0040_services_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkupitems',
            name='slug',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='department',
            name='slug',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='personalpostposition',
            name='slug',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='services',
            name='slug',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
