# Generated by Django 4.0 on 2022-08-20 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0042_department_description_alter_services_service_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена услуги'),
        ),
    ]
