# Generated by Django 4.0 on 2022-08-20 15:50

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0043_alter_services_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='content',
            field=django_quill.fields.QuillField(blank=True, null=True, verbose_name='Описание'),
        ),
    ]
