# Generated by Django 3.2.15 on 2022-09-07 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0045_serviceform'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('slug', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Анализы (Категории)',
                'verbose_name_plural': 'Анализы (Категории)',
            },
        ),
        migrations.AlterField(
            model_name='serviceform',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.services', verbose_name='Услуга'),
        ),
        migrations.CreateModel(
            name='AnalysisSubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('slug', models.CharField(blank=True, max_length=255, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_analysis_category', to='main.analysiscategory', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Анализы (Подкатегории)',
                'verbose_name_plural': 'Анализы (Подкатегории)',
            },
        ),
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена услуги')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_category', to='main.analysissubcategory', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Анализы',
                'verbose_name_plural': 'Анализы',
            },
        ),
    ]
