# Generated by Django 3.2.15 on 2022-09-07 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0046_auto_20220907_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysis',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Выбирается в случае когда нет подкатегории', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analysis_category', to='main.analysissubcategory', verbose_name='Категория'),
        ),
    ]
